##This is the module which takes inputs from the Parser module, and actually coverts a single VM instruction into relevant assmbly code for Hack machine


"""
    Type/Interpretation:
        This module will be responsible for generating the corresponding Hack assembly code for 2 categories of instructions
            - Arithemetic (9 commands): add, sub, neg, eq, gt, lt, and, or , not
            - Memory Access (2 commands): 
                - push <segment> <xxx>
                - pop <segment> <xxx>
                - Segment could be of 8 types: ARG, LCL, THIS, THAT, TEMP, POINTER, STATIC, CONSTANT

        For branching, and function instructions we will wait till module 8 to get that done
        In terms of organisation , this module will offer the following functions:
            - __init__ method which will initialise the object with a filename field, and a list codelist, which will have the assembly instructions we are converting for the given object
            - writeArithemetic method which will operate on C_ARITHEMETIC command type and generate the corresponding Hack assembly code
            - writePushPop method which will operate on pushpop commands and generate the necessary Hack assembly code
            - Private methods to be used by interface methods 
        We will write pseduo assembly for each of the methods, and write helper functions for each of the pseudo assembly code
        Codes generated by writeArithemetic and writePushPop will be appended to the codelist field

"""


class CodeWriter():
    """
    TEMPLATE:
        FIELDS:
            ...self.filename                                                            ...Str
            ...self.codelist                                                            ...List 
            ...self.memorymapping                                                       ...Dictionary
            ...self.arithemeticmap                                                      ...Dictionary
            ...self.label_counter                                                       ...int
        METHODS:
            ...self.__init__(self)                                                 ...No return (only initialises the obejct)
            ...self.writeArithemetic (self, code:Str)                              ...No return (only updates code in codelist for Arithemetic commands)
            ...self.writePushPop (self, code:Str, segment: Str, index: Int)        ...No return (only updates code in codelist for Push Pop commands)
    """
    
    def __init__(self, filename):
        self.filename = filename 
        self.codelist = [] ##this is the list which will be updated as and when a new instruction is decoded
        self.memorymapping = {"argument": "ARG", "local": "LCL", "this": "THIS", "that": "THAT", "temp": "TEMP"}
        self.arithemeticmap = {"add": "+", "sub": "-", "eq":"-", "gt": "-", "lt": "-", "neg": "-", "not": "!", "and": "&", "or": "|"}
        self.label_counter = 0 ##To be utilised for eq, gt, lt subroutines in writeArithemetic routine

    """
    Signature: self, code:Str, segment: Str, index: Int > No return (Updates codelist with the corresponding code)
    Purpose:
        This method is supposed to work on a instruction of type "push/pop segment index" and return the corresponding Hack assembly code as per the following pseudo specifications
            pop segment i: addr = segment + i; SP-- ; *addr = *SP      //DONE
            push segment i: addr=segment + i; *SP = *addr; SP++        //DONE
            push constant i: *SP = i; SP++                             //DONE
            push temp i: addr=5+i; *SP = *addr ; SP++                  //DONE
            pop temp i: addr=5+i; SP--; *addr = *SP                    //DONE
            push static i: addr=filename.i; *SP=*addr;SP++             //DONE
            pop static i: addr=filename.i; SP--; *addr = *SP           //DONE
            push pointer 0/1: *SP = THIS/THAT, SP++                    //DONE
            pop pointer 0/1: SP--; THIS/THAT = *SP                     
        We will also add a comment based code - for e.g. for push constant 100, 1st instruction will always be - "//push constant 100"
        FInal output will be codelist will be updated as "push constant 0": [xx,yy,zz...] 
    """
    def writePushPop(self, code, segment, index):
        templist = [] ##Templist in which we will store the relevant instructions
        templist.append("//"+" "+code+" " +segment + " " + index) ##First instruction becomes comment 
        if code=="push":
            if segment in ["local", "argument", "this", "that", "temp"]:
                templist.extend(self.setARegister(segment, index)) ##Will need to define this later ; this is equivalent to saing addr =segment+1, we will also need to define for temp here
                templist.extend(self.setPointerSPToPointerAddress()) ##Equivalent to *SP = *addr
                templist.extend(self.incrementSP()) ## SP++
            elif segment in ["constant"]:
                templist.extend(self.setPointerSPToValue(index)) ##*SP=i
                templist.extend(self.incrementSP()) ## SP++
            elif segment in ["static"]:
                templist.append("@"+self.filename[:-3]+"."+index) ## this represents that static variable is being defined as @filename.index
                templist.extend(self.setPointerSPToPointerAddress()) ##Equivalent to *SP = *addr
                templist.extend(self.incrementSP()) ## SP++
            elif segment in ["pointer"]:
                if index == "0":
                    templist.extend(self.setPointerSPToValue("THIS")) ##*SP = THIS , Need to configure this in our private method of setpointerSP to value
                if index == "1":
                    templist.extend(self.setPointerSPToValue("THAT")) ## *SP = THAT, Need to configure this in our private method of setpointerSP to value
                templist.extend(self.incrementSP())
        elif code=="pop":
            if segment in ["local", "argument", "this", "that", "temp"]:
                templist.extend(self.setARegister(segment, index))  ## compute addr into A
                templist.extend(["D=A", "@13", "M=D"])              ## save addr to R13
                templist.extend(self.decrementSP())                  ## SP--
                templist.extend(["@SP", "A=M", "D=M"])              ## D = *SP
                templist.extend(["@13", "A=M"])                      ## reload addr
                templist.append("M=D")                               ## *addr = D
            elif segment in ["static"]:
                templist.append("@"+self.filename[:-3]+"."+index)
                templist.extend(["D=A", "@13", "M=D"])              ## save addr to R13, need to save the address or it will get overridden
                templist.extend(self.decrementSP())                  ## SP--
                templist.extend(["@SP", "A=M", "D=M"])              ## D = *SP
                templist.extend(["@13", "A=M"])                      ## reload addr
                templist.append("M=D")                               ## *addr = D

            elif segment in ["pointer"]:
                templist.extend(self.decrementSP()) ##SP--; need to be defined
                templist.extend(self.setThisThatToPointerSP(index)) ##THIS/THAT=*SP , needs to be defined
        
        else:
            raise ValueError("The given command is not suitable for this method")
        self.codelist.extend(templist)  ##finally updating our codelist with the corresponding instruction 
        
                    

    """
    Signature: self, code: Str
    Purpose:
        This method is supposed to work on a instruction of type "add/sub/eq..." and return the corresponding Hack assembly code as per the following pseudo specifications
            add: SP--; addr=*SP; D=*addr; SP--; addr=*SP; D=D + *addr; *addr=D; SP++                                                    //DONE
            sub: ---------------------------------------  D=D - *addr; *addr=D; SP++                                                    //DONE
            eq:  ---------------------------------------  D=D - *addr; addr=IFEQUAL; D;JEQ; *addr=0; SP++ (IFEQUAL); *addr=-1; SP++     //DONE
            gt:  ---------------------------------------  D=D - *addr; addr=IFGT; D;JGT; *addr=0; SP++; (IFGT); *addr=-1; SP++          //DONE
            lt:  ---------------------------------------  D=D - *addr; addr=IFLT; D;JLT; *addr=0; (IFLT); *addr=-1; SP++                //DONE
            and: ---------------------------------------  D=D & *addr; *addr=D; SP++                                                    //DONE
            or:  ---------------------------------------  D=D + *addr; *add=D; SP++                                                      //DONE
            not: SP--; addr=*SP; D=*addr; D= !D; *addr=D; SP++
            neg: ........................ D= -D; *addr=D; SP++
        We will also add a comment based code - for e.g. for push constant 100, 1st instruction will always be - "//push constant 100"
    """
    def writeArithemetic(self, code):
        templist = [] ##Templist in which we will store the relevant instructions
        templist.append("//"+" "+code) ##First instruction becomes comment 
        if code in ["add", "sub", "eq", "gt", "lt", "and", "or"]:
            templist.extend(self.decrementSP()) ##SP--
            templist.extend(self.setARegister("PointerSP", "0")) ##addr=*SP
            templist.extend(self.setDRegisterToComputation(None, None, "PointerAddr"))
            templist.extend(self.decrementSP()) ##SP--
            templist.extend(self.setARegister("PointerSP", "0")) ##addr=*SP
            if code == "add":
                templist.extend(self.setDRegisterToComputation("D","add", "PointerAddr")) ##D=D+*addr
                templist.append("M=D") #*addr=D
                templist.extend(self.incrementSP())
            elif code == "sub":
                templist.append("D=M-D") ## first - second
                templist.append("M=D")
                templist.extend(self.incrementSP())
            elif code == "and":
                templist.extend(self.setDRegisterToComputation("D","and", "PointerAddr")) ##D=D+*addr
                templist.append("M=D") #*addr=D
                templist.extend(self.incrementSP()) ##SP++
            elif code == "or":
                templist.extend(self.setDRegisterToComputation("D","or", "PointerAddr")) ##D=D+*addr
                templist.append("M=D") #*addr=D
                templist.extend(self.incrementSP()) #SP++
            elif code in ["eq", "gt", "lt"]:
                jump_map = {"eq": "JEQ", "gt": "JGT", "lt": "JLT"}
                label = code.upper() + "_" + str(self.label_counter)
                end_label = "END_" + code.upper() + "_" + str(self.label_counter)
                self.label_counter += 1
                templist.append("D=M-D")                                                    ## first - second  ## D = *addr - D
                templist.append("@" + label)                                                ## @IFEQ_0
                templist.append("D;" + jump_map[code])                                      ## D;JEQ
                ## False case
                templist.extend(["@SP", "A=M"])                                             ## reload target address
                templist.append("M=0")                                                      ## *SP = 0 (false)
                templist.extend(self.incrementSP())                                         ## SP++
                templist.append("@" + end_label)                                            ## @END_EQ_0
                templist.append("0;JMP")                                                    ## unconditional jump past true
                ## True case
                templist.append("(" + label + ")")                                          ## (EQ_0)
                templist.extend(["@SP", "A=M"])                                             ## reload target address
                templist.append("M=-1")                                                     ## *SP = -1 (true)
                templist.extend(self.incrementSP())                                         ## SP++
                ## End
                templist.append("(" + end_label + ")")  
        elif code in ["not", "neg"]:
            ##not: SP--; addr=*SP; D=*addr; D= !D; *addr=D; SP++
            ##neg: ........................ D= -D; *addr=D; SP++
            templist.extend(self.decrementSP()) ##SP--
            templist.extend(self.setARegister("PointerSP", "0")) ##addr=*SP
            templist.extend(self.setDRegisterToComputation(None, None, "PointerAddr")) ##D=*addr
            templist.extend(self.setDRegisterToComputation(None, code, "D")) ##D=!D or D=-D
            templist.append("M=D") ##*addr=D
            templist.extend(self.incrementSP())
        else:
            raise ValueError("The given command is not suitable for this method")
        self.codelist.extend(templist) ##finally updating our codelist with the corresponding instruction 
        
        
    ##------------------------------------------------------------------------------------------------------------------------------------------------------------------------##
    ##Below are the functions we wished for above, all of them are supposed to return a list of instructions 

    """
    Signature:self, segment: Str, index: Str > Assembly Code List: List
    Purpose:
        When operating with segment where segment in: ["local", "argument", "this", "that"]:
            - First we will find the mapping of segment from memorymapping
            - Get the actual addresss at that mrmoey mapping  to D register (@memorymapping, D=M)
            - Then we get index to A register (@index)
            - Then we do D=D+A 
            - Then we set A=D
        When we are operating for addr=temp+index, where segment = "temp" and index=index:
            - We will first get 5 to D register (@5, D=A)
            - Then we get index to A register (@index)
            - Then we do D=D+A
            - Then we set A=D
        When we are operating for addr=*SP, where segment = "PointerSP", index=0, here is what we will do:
            - First we get SP to A register , A=SP
            - Then we simply do A=M , which will get the address to 
    """
    def setARegister(self, segment, index):
        templist = []
        if segment in ["local", "argument", "this", "that"]:
            segmentmap = self.memorymapping[segment]
            templist.append("@"+segmentmap)
            templist.append("D=M")
            templist.append("@"+index)
            templist.append("D=D+A")
            templist.append("A=D")
        elif segment == "temp":
            templist.append("@5")
            templist.append("D=A")
            templist.append("@"+index)
            templist.append("D=D+A")
            templist.append("A=D")
        elif segment == "PointerSP":
            templist.append("@SP")
            templist.append("A=M")
        else:
            raise ValueError("This method is not applicable for the given segment value")
        return templist

    """
    Signature: self>Assembly Code List: List
    Purpose:
        *sp=*addr
        We assume that A register is already updated with the right address
        The objective is to realise the following pseudo assmebly *sp=*addr, and it can be done using hte below instructions:
            - We need to understand that in setAregister method, we already have the right address in our A register already, 
            - so we just need (D=M), which will get value at addr in D
            - Let's get the value at *addr which needs to go to *SP (A=D, D=M), now D has the value which needs to be updated 
            - Now let's get to A the address which needs to be updated, or *SP (@SP, A=M), now A has the address which needs to be updated
            - And finally we have (M=D) and we will get our desired output

        Finally we return the list of instructions as templist
    """
    def setPointerSPToPointerAddress(self):
        templist=[]
        templist.append("D=M")
        templist.extend(["@SP", "A=M"])
        templist.append("M=D")
        return templist

    """
    Signature: self> Assembly Code List: List
    Purpose:
        To increment SP value stored at SP memory or RAM[0], which can be done in the following ways:
            - First we get SP to A register (@SP)
            - Then we store SP+1 in D (D=M+1)
            - And finally we get this value in RAM[0] (M=D)
        Finally we return the list of instructions as templist
    """
    def incrementSP(self):
        templist=[]
        templist.append("@SP")
        templist.append("M=M+1")
        return templist

    """
    Signature:  self, value:Str > Assembly Code List: List
    Purpose:
        *SP = i , where i could be some value i such as 1,2,3, or could be a pre-defined variable THIS or THAT
        For both the cases, list of instructions is same as follows:
            - Since we can't directly do M=value, we need to first get teh corresponidng value in D using (@value, D=A)
            - And then We simply get the address to be updated as folows (@SP, A=M)
            - And then update this to the value from the D register (M=D)
        Finally we return the list of instructions as templist
    """
    def setPointerSPToValue(self, value):
        templist = []
        if value not in ["THIS", "THAT"]:
            templist.extend(["@" + value, "D=A"])
        else:
            templist.extend(["@" + value, "D=M"])
        templist.extend(["@SP", "A=M"])
        templist.append("M=D")
        return templist

    
    """
    
    Signature: self> Assembly Code List: List
    Purpose:
        To decrement SP value stored at SP memory or RAM[0], which can be done in the following ways:
            - First we get SP to A register (@SP)
            - Then we store SP+1 in D (D=M-1)
            - And finally we get this value in RAM[0] (M=D)
        Finally we return the list of instructions as templist
    """
    def decrementSP(self):
        templist=[]
        templist.append("@SP")
        templist.append("M=M-1")
        return templist

    """
    Signature: self, value:Str > Assembly Code List: List
    Purpose:
        
        Assuming that A register is already filled up with relevant address, his function solves for the following  cases:
            - *addr=*SP , this is applicable when value == "PointerSP", and will have the following instrucitons:
                - Let's store the address value in D first and then somewhere safe (D=A, @13, M=D) ##Now 13 has the address which is to be updted
                - Then let's get the value which needs to be updated (@SP, A=M, D=M) // Now D has the value which needs to be udpated
                - Now let's again load the address which needs to be updated (@13, A=M)
                - And now, finally we update the address (M=D) and our #addr will be updated with *SP
            - *addr=D, this shouldnt be too difficult:
                - We do (A=M) ## Now A has the address which is to be updated
                - And we imply copy the value of D to M (M=D)
            - *addr=0/1, should be straightforward:
                - We first get the address to be updated (A=M)
                - And then simply update it to the value passed (M=value)

        Finally we return the list of instructions as templist

    """
    def setAddressPointerToValue(self, value):
        templist = []
        if value == "PointerSP":
            templist.extend(["D=A", "@13", "M=D"])
            templist.extend(["@SP", "A=M", "D=M"])
            templist.extend(["@13", "A=M"])
            templist.append("M=D")
        elif value == "D":
            templist.append("A=M")
            templist.append("M=D")
        elif value in ["0", "-1"]:
            templist.append("A=M")
            templist.append("M="+value)
        else:
            raise ValueError("Please pass the right value for this method")
        return templist


    """
    Signature : self, index:Str > Assembly Code List: List
    Purpose:
        If index == "0" > THIS=*SP
        If index == "1" > THAT=*SP
        Here is the instruction, for THIS:
            - Get value to be updated in D (@SP, A=M D=M)
            - Now get THIS on A and update it (@THIS, M=D)
        We follow the same for THAT
        Finally we return the list of instructions as templist

    """
    def setThisThatToPointerSP(self, index):
        templist = []
        templist.extend(["@SP", "A=M","D=M"])
        if index == "0":
            templist.extend(["@THIS", "M=D"])
        elif index == "1":
            templist.extend(["@THAT", "M=D"])
        else:
            raise ValueError("Please pass the right index for this method")
        return templist
        

    """
    Signature: self, value1: None or Str, operation: None or Str, value2: Str > Assembly Code List:List
    Purpose:
        Will solve for the following possibilities:
            - D= *addr, when value1=None, operation=None, value2=*addr
                - This is simply solved by doing (D=M)
            - D= -D or D=!D, when value1=None, operation = neg or not, value2=D
                - This is simply achieved by doing (D=[operation]D)
            - D= D (opearation) *addr, this will also be straightforward
                - D = D [operation] M
        Finally we return the list of instructions as templist
    """
    def setDRegisterToComputation(self, value1, operation, value2):
        templist= []
        if value1==None and operation == None:
            templist.append("D=M")
        elif value1 == None:
            templist.append("D="+self.arithemeticmap[operation]+"D")
        else:
            templist.append("D=D"+self.arithemeticmap[operation]+"M")
        return templist


