##This is the module which takes inputs from the Parser module, and actually coverts a single VM instruction into relevant assmbly code for Hack machine

##IMPORTANT: FUNCTIONALITY TO TRANSLATE MULTIPLE .VM FILES WILL BE HANDLED IN THE MAIN.PY FILE, HERE WE ARE ONLY ADDING FUNCTIONALITY TO BOOTSTRAP, AND DECODE FUNCTION, BRANCH COMMANDS

"""
    Type/Interpretation:
        This module is an extension of the CodeWriter developed for Project 7
        We will add functionality to translate BRANCHING and FUNCTION commands
        This module will be responsible for generating the corresponding Hack assembly code for 2 categories of instructions
            - Arithemetic (9 commands): add, sub, neg, eq, gt, lt, and, or , not
            - Memory Access (2 commands): 
                - push <segment> <xxx>
                - pop <segment> <xxx>
                - Segment could be of 8 types: ARG, LCL, THIS, THAT, TEMP, POINTER, STATIC, CONSTANT
            - Branching (3 commands):
                - label <label>
                - goto <label>
                - if-goto <label>
            - Function (3 commands):
                - function <functionName> <nVars>
                - call <functionName> <nArgs>
                - return

        In terms of organisation , this module will offer the following functions:
            - __init__ method:
                - which will initialise the object with a filename field, and a list codelist, which will have the assembly instructions we are converting for the given object
                - It will also initiate the bootstrap code in the codelist, which will initialise base instructions such as SP=256, call sys.init etc.
            - writeArithemetic method which will operate on C_ARITHEMETIC command type and generate the corresponding Hack assembly code
            - writePushPop method which will operate on pushpop commands and generate the necessary Hack assembly code
            - Private methods for writeArithemetic and writePushPop to be used by interface methods 
            NEW METHODS
            - writeLabel - which will operate on label commands
            - writeGoTo - which will generate relevant assembly for GoTo commands
            - writeIf - operates of if-goto commands and generates relevant assembly code
            - writeFunction - operates on "function funcName nVars" type of command, and geenrates assembly
            - writeCall - operates on "call funcName nArgs" type of command
            - writeReturn - generates assembly for "return" VM code
        We will write pseduo assembly for each of the methods, and write helper functions for each of the pseudo assembly code
        Codes generated by all the write<xxx> methods will be appended to the codelist field

"""
class CodeWriter():
    """
    TEMPLATE:
        FIELDS:
            ...self.filename                                                            ...Str
            ...self.codelist                                                            ...List 
            ...self.memorymapping                                                       ...Dictionary
            ...self.arithemeticmap                                                      ...Dictionary
            ...self.label_counter                                                       ...int
            ...self.current_function                                                    ...Str
            ...self.current_return                                                      ...int
        METHODS:
            ...self.__init__(self)                                                 ...No return (only initialises the obejct)
            ...self.writeArithemetic (self, code:Str)                              ...No return (only updates code in codelist for Arithemetic commands)
            ...self.writePushPop (self, code:Str, segment: Str, index: Int)        ...No return (only updates code in codelist for Push Pop commands)
            ...self.writeLabel(self, code:Str, label: Str)                         ...No return (only updates code in codelist for label command)
            ...self.writeGoTo(self, code:Str, label: Str)                          ...No return (only updates code in codelist for GoTo command)
            ...self.writeIf(self, code:Str, label: Str)                            ...No return (only updates code in codelist for If-GoTo command)
            ...self.writeFunction(self, code:Str, funcname: Str, nVars: Str)       ...No return (only updates code in codelist for Function command)
            ...self.writeCall(self, code:Str, funcname: Str, nArgs: Str)           ...No return (only updates code in codelist for label command)
            ...self.writeReturn(self, code:Str)                                    ...No return (only updates code in codelist for return command)
    """
    
    def __init__(self, filename, bootstrap = False):
        self.filename = filename 
        self.codelist = []
        
        self.memorymapping = {"argument": "ARG", "local": "LCL", "this": "THIS", "that": "THAT", "temp": "TEMP"}
        self.arithemeticmap = {"add": "+", "sub": "-", "eq":"-", "gt": "-", "lt": "-", "neg": "-", "not": "!", "and": "&", "or": "|"}
        self.label_counter = 0 ##To be utilised for eq, gt, lt subroutines in writeArithemetic routine
        self.current_function = "" ##This will be updated when we call the writeFunction method
        self.current_return = 0 ##Will be used for multiple calls inside a single function 
        if bootstrap:
            self.codelist = ["@256", "D=A", "@SP","M=D" ] ##we initialise the list to start wit SP=256, and call Sys.init
            self.writeCall("call", "Sys.init", "0") ##to bootstrap our code

    ##---------------------------------------------------------------BRANCHING METHODS----------------------------------------------------------------------------------------------##
    ##ALL these functions to be used only for label variables - such as (LOOP) or (END), for functions, and rteturn labels, we will use separate private methods
    """
    Signature: self, code:Str, label:Str > No return (Updates codelist with relevant assembly code)
    Purpose:
        First we will need to modify the label to be of value <self.filename>.<self.current_function>$<label>
        Will translate commands of type "label xxx" into assembly - which will be simply (xxx)
        arg1 will be "label" and arg2 will be "xxx" here
    """
    def writeLabel(self,code, label):
        templist = []
        if code == "label":
            templist.append("(" + self.current_function + "$" + label + ")")
        else:
            raise ValueError("The given command is not suitable for this method")
        self.codelist.extend(templist) ##updating our codelist with the corresponding instruction

    
    """
    Signature: self, code:Str, label: Str > No return (Updates codelist with relevant assembly code)
    Purpose:
        First we will need to modify the label to be of value <self.filename>.<self.current_function>$<label>
        Instruction of type "goto <xxx>", and will translate into an unconditional jump to label <xxx> == (@xxx, 0; JMP)
        arg1 will be "goto" and arg2 will be <xxx> here
    """
    def writeGo(self, code, label):
        templist = []
        if code == "goto":
            templist.extend(["@" + self.current_function + "$" + label, "0;JMP"])
        else:
            raise ValueError("The given command is not suitable for this method")
        self.codelist.extend(templist) ##updating our codelist with the corresponding instruction

    
    """
    Signature: self, code:Str, label: Str > No return (Updates codelist with relevant assembly code)
    Purpose:
        
        First we will need to modify the label to be of value <self.filename>.<self.current_function>$<label>
        Check topmost value of stack - if it is not 0 , jump to the given label, otherwise dont make the jump, this can be executed with the following instructions:
            - First we will get SP backwards , SP--
            - Get the top most value of stack - (@SP, A=M, D=M) ##this gets the topmost value in D
            - Next upload the label , and make the comparison (@Label, D;JNE) 
            - Ideally D = -1 would mean top most value of stack is true, so to check that we compute D+1, which when it is zero means D=-1, means D=true, and we have to jump
    """
    def writeIf(self, code, label):
        templist = []
        if code == "if-goto":
            templist.extend(self.decrementSP())
            templist.extend(["@SP", "A=M", "D=M"]) 
            templist.extend(["@" + self.current_function + "$" + label, "D;JNE"])
        else:
            raise ValueError("The given command is not suitable for this method")
        self.codelist.extend(templist) ##updating our codelist with the corresponding instruction
        

    ##---------------------------------------------------------------FUNCTION METHODS----------------------------------------------------------------------------------------------##

    """
    Signature: self, code: Str, funcName: Str, nVars:Str >No return (UPdates codelist with relevant assembly code)
    Purpose:
        Declares a functino funcName, informing that the function has nVars local variables 
        Decode function funcName nVars ; through the following semantics:
            - We will first store the functionaName in self.current_function (for use in our branching/label commands), and then 
            - Define a new function variable but preceded by the file name: ((self.filename.funcName))
            - Then run a loop nVars times, and for each iteration go for push constant 0
        Since we will be using intnarl method (writePushPop) which directly updates codlist, hence here we will directly update code list
    """
    def writeFunction(self, code, funcName, nVars):
        templist = []
        if code == "function":
            self.current_return = 0 ##For every new function we start current_return from 0
            self.current_function = funcName ##We first update the current function name in our fields 
            self.codelist.append("("+self.current_function+")") ## We define a new label for our function
            for i in range(int(nVars)):
                self.writePushPop("push", "constant", "0") ##We run the loop n times to push for 0 value in LCL
        else:
            raise ValueError("The given command is not suitable for this method")
        



    """
    Signature: self, code:Str, funcName: Str, nArgs: Str > No return (Updates codelist with relevant assembly code)
    Purpose: 
        Calls a function funcName, informing that nArgs arguments were pushed to the stack before the call 
        First thing first, we will need to modify the funcName to modified name which is <filename>.<funcname> - we have to go to this label 
        Then we execute the following instructions:
            - push returnAddress //Generates a label and pushes it to stack (..., SP++)
            - push LCL //saves LCL of the caller (@LCL, D=M, @SP, M=D, SP++)
            - push ARG //saves ARG of the caler (@ARG, D=M, @SP, M=D, SP++)
            - push THIS //saves THIS of the caler (@THIS, D=M, @SP, M=D, SP++)
            - push THAT //saves THAT of the caler (@THAT, D=M, @SP, M=D, SP++)
            - ARG = SP-5-nArgs //repositions Args for the callee function (@SP, D=A, @5, D=D-A, @nArgs, D=D-A, @ARG, M=D)
            - LCL = SP //repositions LCL for the callee function (@SP, D=M, @LCL, M=D)
            - goto f //make an unconditional jump to the given function (@filename.funcName, 0;JMP)
            - (returnAddress) //injects the return address label in to the code
        Eventually everything will be pushed to templist
    """

    def writeCall(self, code, funcName, nArgs):
        templist = []
        if code == "call":
            returnAddress = self.current_function + "$ret." + str(self.current_return) ##Defining the return address label
            self.current_return = self.current_return + 1 ##Increasing the current return, for the current function 
            templist.extend(["@"+returnAddress, "D=A", "@SP", "A=M", "M=D"]) ## pushing return adddress to the stack
            templist.extend(self.incrementSP()) ##SP++ for push operation
            templist.extend(["@LCL", "D=M", "@SP", "A=M", "M=D"]) ##Pushing LCL address pointer to the stack 
            templist.extend(self.incrementSP()) ##SP++ for push operation
            templist.extend(["@ARG", "D=M", "@SP", "A=M", "M=D"]) ##Pushing ARG address pointer to the stack 
            templist.extend(self.incrementSP()) ##SP++ for push operation
            templist.extend(["@THIS", "D=M", "@SP", "A=M", "M=D"]) ##Pushing THIS address pointer to the stack 
            templist.extend(self.incrementSP()) ##SP++ for push operation
            templist.extend(["@THAT", "D=M", "@SP", "A=M", "M=D"]) ##Pushing ARG address pointer to the stack 
            templist.extend(self.incrementSP()) ##SP++ for push operation
            templist.extend(["@SP", "D=M", "@5", "D=D-A", "@"+nArgs, "D=D-A", "@ARG", "M=D"]) ## ARG = SP-5-nArgs //repositioning arg for callee funciton
            templist.extend(["@SP", "D=M", "@LCL", "M=D"]) ##repositioning lcl for the callee function
            templist.extend(["@"+funcName, "0;JMP"]) ##jumping to the call function label
            templist.append("(" + returnAddress + ")") ##injecting return addresslabelin to the code
        else:
            raise ValueError("The given command is not suitable for this method")
        self.codelist.extend(templist) ##updating our codelist with the corresponding instruction


    """
    Signature: self, code: Str > No return (Updates codelist with relevant assembly code)
    Purpose:
        Terminates the current fucntion, and returns control to the caller
        We neeed to follow the following steps here:
            - frame = LCL ##Store the start of the function stack in a temp (RAM[13]) variable (@LCL, A=M, D=A, @13, M=D) , RAM[13] has the address pointer of LCL
            - retAddress = *(frame-5) put the returnAddress in a temp (RAM[14]) variable (@13, A=M, A=M, D=A, @5, D=D-A, @14, M=D) , now RAM[14] has the returnAddress
            - *ARG=pop() - repositions the return value of the caller (SP--, @SP, A=M, A=M, D=A, @ARG, A=M, M=D) - this will get the top value of stack at *arg
            - SP = ARG + 1 - repositions SP to just after ARG (@ARG, D=M, @SP, M=D+1)
            - THAT = *(frame-1) ##restores THAT for the caller (@13, D=M-1, A=D, D=M, @THAT, M=D)
            - THIS = *(frame - 2) ##restores THIS for the caller (@13, D = M, @2, D=D-A, A=D, D=M, @THIS, M=D)
            - ARG = *(frame - 3) ##restores ARG for the caller (@13, D = M, @3, D=D-A, A=D, D=M, @ARG, M=D)
            - LCL = *(frame - 4) ## restres LCL for the caller (@13, D = M, @4, D=D-A, A=D, D=M, @LCL, M=D)
            - gotoretAddr ##Jump back to the caller function (@14, A=M, 0;JMP)
        Eventually everything will be pushed to templist
    """
    def writeReturn(self,code):
        templist = []
        if code == "return":
            templist.extend(["@LCL", "A=M", "D=A", "@13", "M=D"]) ## frame = LCL, here frame is in RAM[13]
            templist.extend(["@13", "A=M", "D=A", "@5", "D=D-A", "A=D", "D=M", "@14", "M=D"]) ##retAddress = *(frame-5)
            templist.extend(self.decrementSP()) ##1st step for *ARG = pop
            templist.extend(["@SP", "A=M", "D=M", "@ARG", "A=M", "M=D"]) ##2nd step for *arg = pop
            templist.extend(["@ARG", "D=M", "D=D+1", "@SP", "M=D"])  ## SP = ARG + 1
            templist.extend(["@13", "D=M-1", "A=D", "D=M", "@THAT", "M=D"]) ##THAT = *(Frame - 1)
            templist.extend(["@13", "D=M", "@2", "D=D-A", "A=D", "D=M", "@THIS", "M=D"]) ##THIS = *(Frame - 2)
            templist.extend(["@13", "D=M", "@3", "D=D-A", "A=D", "D=M", "@ARG", "M=D"]) ##ARG=(*frame - 3)
            templist.extend(["@13", "D=M", "@4", "D=D-A", "A=D", "D=M", "@LCL", "M=D"]) ##LCL = *(Frame-4)
            templist.extend(["@14", "A=M", "0;JMP"])
        else:
            raise ValueError("The given command is not suitable for this method")
        self.codelist.extend(templist) ##updating our codelist with the corresponding instruction

    
    
    ##-----------------------------------------------------------------PUSHPOP AND ARITHEMETIC COMMANDS-----------------------------------------------------------------------------------------------##
    """
    Signature: self, code:Str, segment: Str, index: Int > No return (Updates codelist with the corresponding code)
    Purpose:
        This method is supposed to work on a instruction of type "push/pop segment index" and return the corresponding Hack assembly code as per the following pseudo specifications
            pop segment i: addr = segment + i; SP-- ; *addr = *SP      //DONE
            push segment i: addr=segment + i; *SP = *addr; SP++        //DONE
            push constant i: *SP = i; SP++                             //DONE
            push temp i: addr=5+i; *SP = *addr ; SP++                  //DONE
            pop temp i: addr=5+i; SP--; *addr = *SP                    //DONE
            push static i: addr=filename.i; *SP=*addr;SP++             //DONE
            pop static i: addr=filename.i; SP--; *addr = *SP           //DONE
            push pointer 0/1: *SP = THIS/THAT, SP++                    //DONE
            pop pointer 0/1: SP--; THIS/THAT = *SP                     
        We will also add a comment based code - for e.g. for push constant 100, 1st instruction will always be - "//push constant 100"
        FInal output will be codelist will be updated as "push constant 0": [xx,yy,zz...] 
    """
    def writePushPop(self, code, segment, index):
        templist = [] ##Templist in which we will store the relevant instructions
        templist.append("//"+" "+code+" " +segment + " " + index) ##First instruction becomes comment 
        if code=="push":
            if segment in ["local", "argument", "this", "that", "temp"]:
                templist.extend(self.setARegister(segment, index)) ##Will need to define this later ; this is equivalent to saing addr =segment+1, we will also need to define for temp here
                templist.extend(self.setPointerSPToPointerAddress()) ##Equivalent to *SP = *addr
                templist.extend(self.incrementSP()) ## SP++
            elif segment in ["constant"]:
                templist.extend(self.setPointerSPToValue(index)) ##*SP=i
                templist.extend(self.incrementSP()) ## SP++
            elif segment in ["static"]:
                templist.append("@"+self.filename[:-3]+"."+index) ## this represents that static variable is being defined as @filename.index
                templist.extend(self.setPointerSPToPointerAddress()) ##Equivalent to *SP = *addr
                templist.extend(self.incrementSP()) ## SP++
            elif segment in ["pointer"]:
                if index == "0":
                    templist.extend(self.setPointerSPToValue("THIS")) ##*SP = THIS , Need to configure this in our private method of setpointerSP to value
                if index == "1":
                    templist.extend(self.setPointerSPToValue("THAT")) ## *SP = THAT, Need to configure this in our private method of setpointerSP to value
                templist.extend(self.incrementSP())
        elif code=="pop":
            if segment in ["local", "argument", "this", "that", "temp"]:
                templist.extend(self.setARegister(segment, index))  ## compute addr into A
                templist.extend(["D=A", "@13", "M=D"])              ## save addr to R13
                templist.extend(self.decrementSP())                  ## SP--
                templist.extend(["@SP", "A=M", "D=M"])              ## D = *SP
                templist.extend(["@13", "A=M"])                      ## reload addr
                templist.append("M=D")                               ## *addr = D
            elif segment in ["static"]:
                templist.append("@"+self.filename[:-3]+"."+index)
                templist.extend(["D=A", "@13", "M=D"])              ## save addr to R13, need to save the address or it will get overridden
                templist.extend(self.decrementSP())                  ## SP--
                templist.extend(["@SP", "A=M", "D=M"])              ## D = *SP
                templist.extend(["@13", "A=M"])                      ## reload addr
                templist.append("M=D")                               ## *addr = D

            elif segment in ["pointer"]:
                templist.extend(self.decrementSP()) ##SP--; need to be defined
                templist.extend(self.setThisThatToPointerSP(index)) ##THIS/THAT=*SP , needs to be defined
        
        else:
            raise ValueError("The given command is not suitable for this method")
        self.codelist.extend(templist)  ##finally updating our codelist with the corresponding instruction 
        
                    

    """
    Signature: self, code: Str
    Purpose:
        This method is supposed to work on a instruction of type "add/sub/eq..." and return the corresponding Hack assembly code as per the following pseudo specifications
            add: SP--; addr=*SP; D=*addr; SP--; addr=*SP; D=D + *addr; *addr=D; SP++                                                    //DONE
            sub: ---------------------------------------  D=D - *addr; *addr=D; SP++                                                    //DONE
            eq:  ---------------------------------------  D=D - *addr; addr=IFEQUAL; D;JEQ; *addr=0; SP++ (IFEQUAL); *addr=-1; SP++     //DONE
            gt:  ---------------------------------------  D=D - *addr; addr=IFGT; D;JGT; *addr=0; SP++; (IFGT); *addr=-1; SP++          //DONE
            lt:  ---------------------------------------  D=D - *addr; addr=IFLT; D;JLT; *addr=0; (IFLT); *addr=-1; SP++                //DONE
            and: ---------------------------------------  D=D & *addr; *addr=D; SP++                                                    //DONE
            or:  ---------------------------------------  D=D + *addr; *add=D; SP++                                                      //DONE
            not: SP--; addr=*SP; D=*addr; D= !D; *addr=D; SP++
            neg: ........................ D= -D; *addr=D; SP++
        We will also add a comment based code - for e.g. for push constant 100, 1st instruction will always be - "//push constant 100"
    """
    def writeArithemetic(self, code):
        templist = [] ##Templist in which we will store the relevant instructions
        templist.append("//"+" "+code) ##First instruction becomes comment 
        if code in ["add", "sub", "eq", "gt", "lt", "and", "or"]:
            templist.extend(self.decrementSP()) ##SP--
            templist.extend(self.setARegister("PointerSP", "0")) ##addr=*SP
            templist.extend(self.setDRegisterToComputation(None, None, "PointerAddr"))
            templist.extend(self.decrementSP()) ##SP--
            templist.extend(self.setARegister("PointerSP", "0")) ##addr=*SP
            if code == "add":
                templist.extend(self.setDRegisterToComputation("D","add", "PointerAddr")) ##D=D+*addr
                templist.append("M=D") #*addr=D
                templist.extend(self.incrementSP())
            elif code == "sub":
                templist.append("D=M-D") ## first - second
                templist.append("M=D")
                templist.extend(self.incrementSP())
            elif code == "and":
                templist.extend(self.setDRegisterToComputation("D","and", "PointerAddr")) ##D=D+*addr
                templist.append("M=D") #*addr=D
                templist.extend(self.incrementSP()) ##SP++
            elif code == "or":
                templist.extend(self.setDRegisterToComputation("D","or", "PointerAddr")) ##D=D+*addr
                templist.append("M=D") #*addr=D
                templist.extend(self.incrementSP()) #SP++
            elif code in ["eq", "gt", "lt"]:
                jump_map = {"eq": "JEQ", "gt": "JGT", "lt": "JLT"}
                label = code.upper() + "_" + str(self.label_counter)
                end_label = "END_" + code.upper() + "_" + str(self.label_counter)
                self.label_counter += 1
                templist.append("D=M-D")                                                    ## first - second  ## D = *addr - D
                templist.append("@" + label)                                                ## @IFEQ_0
                templist.append("D;" + jump_map[code])                                      ## D;JEQ
                ## False case
                templist.extend(["@SP", "A=M"])                                             ## reload target address
                templist.append("M=0")                                                      ## *SP = 0 (false)
                templist.extend(self.incrementSP())                                         ## SP++
                templist.append("@" + end_label)                                            ## @END_EQ_0
                templist.append("0;JMP")                                                    ## unconditional jump past true
                ## True case
                templist.append("(" + label + ")")                                          ## (EQ_0)
                templist.extend(["@SP", "A=M"])                                             ## reload target address
                templist.append("M=-1")                                                     ## *SP = -1 (true)
                templist.extend(self.incrementSP())                                         ## SP++
                ## End
                templist.append("(" + end_label + ")")  
        elif code in ["not", "neg"]:
            ##not: SP--; addr=*SP; D=*addr; D= !D; *addr=D; SP++
            ##neg: ........................ D= -D; *addr=D; SP++
            templist.extend(self.decrementSP()) ##SP--
            templist.extend(self.setARegister("PointerSP", "0")) ##addr=*SP
            templist.extend(self.setDRegisterToComputation(None, None, "PointerAddr")) ##D=*addr
            templist.extend(self.setDRegisterToComputation(None, code, "D")) ##D=!D or D=-D
            templist.append("M=D") ##*addr=D
            templist.extend(self.incrementSP())
        else:
            raise ValueError("The given command is not suitable for this method")
        self.codelist.extend(templist) ##finally updating our codelist with the corresponding instruction 
        
        
    ##-------------------------------------------------------PRIVATE METHODS FOR PUSHPOP & ARITHEMETIC COMMANDS-----------------------------------------------------------------------------------------------------##
    ##Below are the functions we wished for above, all of them are supposed to return a list of instructions 

    """
    Signature:self, segment: Str, index: Str > Assembly Code List: List
    Purpose:
        When operating with segment where segment in: ["local", "argument", "this", "that"]:
            - First we will find the mapping of segment from memorymapping
            - Get the actual addresss at that mrmoey mapping  to D register (@memorymapping, D=M)
            - Then we get index to A register (@index)
            - Then we do D=D+A 
            - Then we set A=D
        When we are operating for addr=temp+index, where segment = "temp" and index=index:
            - We will first get 5 to D register (@5, D=A)
            - Then we get index to A register (@index)
            - Then we do D=D+A
            - Then we set A=D
        When we are operating for addr=*SP, where segment = "PointerSP", index=0, here is what we will do:
            - First we get SP to A register , A=SP
            - Then we simply do A=M , which will get the address to 
    """
    def setARegister(self, segment, index):
        templist = []
        if segment in ["local", "argument", "this", "that"]:
            segmentmap = self.memorymapping[segment]
            templist.append("@"+segmentmap)
            templist.append("D=M")
            templist.append("@"+index)
            templist.append("D=D+A")
            templist.append("A=D")
        elif segment == "temp":
            templist.append("@5")
            templist.append("D=A")
            templist.append("@"+index)
            templist.append("D=D+A")
            templist.append("A=D")
        elif segment == "PointerSP":
            templist.append("@SP")
            templist.append("A=M")
        else:
            raise ValueError("This method is not applicable for the given segment value")
        return templist

    """
    Signature: self>Assembly Code List: List
    Purpose:
        *sp=*addr
        We assume that A register is already updated with the right address
        The objective is to realise the following pseudo assmebly *sp=*addr, and it can be done using hte below instructions:
            - We need to understand that in setAregister method, we already have the right address in our A register already, 
            - so we just need (D=M), which will get value at addr in D
            - Let's get the value at *addr which needs to go to *SP (A=D, D=M), now D has the value which needs to be updated 
            - Now let's get to A the address which needs to be updated, or *SP (@SP, A=M), now A has the address which needs to be updated
            - And finally we have (M=D) and we will get our desired output

        Finally we return the list of instructions as templist
    """
    def setPointerSPToPointerAddress(self):
        templist=[]
        templist.append("D=M")
        templist.extend(["@SP", "A=M"])
        templist.append("M=D")
        return templist

    """
    Signature: self> Assembly Code List: List
    Purpose:
        To increment SP value stored at SP memory or RAM[0], which can be done in the following ways:
            - First we get SP to A register (@SP)
            - Then we store SP+1 in D (D=M+1)
            - And finally we get this value in RAM[0] (M=D)
        Finally we return the list of instructions as templist
    """
    def incrementSP(self):
        templist=[]
        templist.append("@SP")
        templist.append("M=M+1")
        return templist

    """
    Signature:  self, value:Str > Assembly Code List: List
    Purpose:
        *SP = i , where i could be some value i such as 1,2,3, or could be a pre-defined variable THIS or THAT
        For both the cases, list of instructions is same as follows:
            - Since we can't directly do M=value, we need to first get teh corresponidng value in D using (@value, D=A)
            - And then We simply get the address to be updated as folows (@SP, A=M)
            - And then update this to the value from the D register (M=D)
        Finally we return the list of instructions as templist
    """
    def setPointerSPToValue(self, value):
        templist = []
        if value not in ["THIS", "THAT"]:
            templist.extend(["@" + value, "D=A"])
        else:
            templist.extend(["@" + value, "D=M"])
        templist.extend(["@SP", "A=M"])
        templist.append("M=D")
        return templist

    
    """
    
    Signature: self> Assembly Code List: List
    Purpose:
        To decrement SP value stored at SP memory or RAM[0], which can be done in the following ways:
            - First we get SP to A register (@SP)
            - Then we store SP+1 in D (D=M-1)
            - And finally we get this value in RAM[0] (M=D)
        Finally we return the list of instructions as templist
    """
    def decrementSP(self):
        templist=[]
        templist.append("@SP")
        templist.append("M=M-1")
        return templist

    """
    Signature: self, value:Str > Assembly Code List: List
    Purpose:
        
        Assuming that A register is already filled up with relevant address, his function solves for the following  cases:
            - *addr=*SP , this is applicable when value == "PointerSP", and will have the following instrucitons:
                - Let's store the address value in D first and then somewhere safe (D=A, @13, M=D) ##Now 13 has the address which is to be updted
                - Then let's get the value which needs to be updated (@SP, A=M, D=M) // Now D has the value which needs to be udpated
                - Now let's again load the address which needs to be updated (@13, A=M)
                - And now, finally we update the address (M=D) and our #addr will be updated with *SP
            - *addr=D, this shouldnt be too difficult:
                - We do (A=M) ## Now A has the address which is to be updated
                - And we imply copy the value of D to M (M=D)
            - *addr=0/1, should be straightforward:
                - We first get the address to be updated (A=M)
                - And then simply update it to the value passed (M=value)

        Finally we return the list of instructions as templist

    """
    def setAddressPointerToValue(self, value):
        templist = []
        if value == "PointerSP":
            templist.extend(["D=A", "@13", "M=D"])
            templist.extend(["@SP", "A=M", "D=M"])
            templist.extend(["@13", "A=M"])
            templist.append("M=D")
        elif value == "D":
            templist.append("A=M")
            templist.append("M=D")
        elif value in ["0", "-1"]:
            templist.append("A=M")
            templist.append("M="+value)
        else:
            raise ValueError("Please pass the right value for this method")
        return templist


    """
    Signature : self, index:Str > Assembly Code List: List
    Purpose:
        If index == "0" > THIS=*SP
        If index == "1" > THAT=*SP
        Here is the instruction, for THIS:
            - Get value to be updated in D (@SP, A=M D=M)
            - Now get THIS on A and update it (@THIS, M=D)
        We follow the same for THAT
        Finally we return the list of instructions as templist

    """
    def setThisThatToPointerSP(self, index):
        templist = []
        templist.extend(["@SP", "A=M","D=M"])
        if index == "0":
            templist.extend(["@THIS", "M=D"])
        elif index == "1":
            templist.extend(["@THAT", "M=D"])
        else:
            raise ValueError("Please pass the right index for this method")
        return templist
        

    """
    Signature: self, value1: None or Str, operation: None or Str, value2: Str > Assembly Code List:List
    Purpose:
        Will solve for the following possibilities:
            - D= *addr, when value1=None, operation=None, value2=*addr
                - This is simply solved by doing (D=M)
            - D= -D or D=!D, when value1=None, operation = neg or not, value2=D
                - This is simply achieved by doing (D=[operation]D)
            - D= D (opearation) *addr, this will also be straightforward
                - D = D [operation] M
        Finally we return the list of instructions as templist
    """
    def setDRegisterToComputation(self, value1, operation, value2):
        templist= []
        if value1==None and operation == None:
            templist.append("D=M")
        elif value1 == None:
            templist.append("D="+self.arithemeticmap[operation]+"D")
        else:
            templist.append("D=D"+self.arithemeticmap[operation]+"M")
        return templist


    
